# Generated by Django 4.1 on 2023-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("artist", models.TextField()),
                ("img", models.ImageField(upload_to="")),
                ("audioFile", models.FileField(blank=True, null=True, upload_to="")),
                ("audiolink", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
